// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLDp_S_UGPSa1p7HWovuAyM5cTM5NHTMs',
    appId: '1:905288604776:web:6e8fbff0eb73f0dfbf6fdd',
    messagingSenderId: '905288604776',
    projectId: 'halo-2ab0e',
    authDomain: 'halo-2ab0e.firebaseapp.com',
    storageBucket: 'halo-2ab0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRAyYTZs5E11B893KmR-0xfVbD36aWTrs',
    appId: '1:905288604776:android:23f21a1e13381c20bf6fdd',
    messagingSenderId: '905288604776',
    projectId: 'halo-2ab0e',
    storageBucket: 'halo-2ab0e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLDp_S_UGPSa1p7HWovuAyM5cTM5NHTMs',
    appId: '1:905288604776:web:0a8d5208145a0f2bbf6fdd',
    messagingSenderId: '905288604776',
    projectId: 'halo-2ab0e',
    authDomain: 'halo-2ab0e.firebaseapp.com',
    storageBucket: 'halo-2ab0e.firebasestorage.app',
  );
}
